src/main/java/jp/co/surveyAlh/dto/UserDto.java
package jp.co.surveyAlh.dto;

import java.sql.Date;

public class UserDto {
	private int id;
	private String loginId;
	private String name;
	private String password;
	private String passwordConfirmation;
	private Date createdDate;
	private Date updatedDate;
	// 診断結果の値
	private int driveNumber;
	private int volunteerNumber;
	private int analyzeNumber;
	private int createNumber;


	public int getDriveNumber() {
		return driveNumber;
	}

	public void setDriveNumber(int driveNumber) {
		this.driveNumber = driveNumber;
	}

	public int getVolunteerNumber() {
		return volunteerNumber;
	}

	public void setVolunteerNumber(int volunteerNumber) {
		this.volunteerNumber = volunteerNumber;
	}

	public int getAnalyzeNumber() {
		return analyzeNumber;
	}

	public void setAnalyzeNumber(int analyzeNumber) {
		this.analyzeNumber = analyzeNumber;
	}

	public int getCreateNumber() {
		return createNumber;
	}

	public void setCreateNumber(int createNumber) {
		this.createNumber = createNumber;
	}

	public Date getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}
	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public void setPasswordConfirmation(String passwordConfirmation) {
		this.passwordConfirmation = passwordConfirmation;
	}
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getPasswordConfirmation() {
		return passwordConfirmation;
	}
	public void setPasswordConfirmtion(String passwordConfirmation) {
		this.passwordConfirmation = passwordConfirmation;
	}


	/**
	 * 診断結果から性格のタイプを返す
	 * */
	public String getPersonalityType() {

		// 診断しているかを確認
		if (!checkResult()) {
			return "";
		}

		if (driveNumber < volunteerNumber) {
			return "ボランティア";
		} else if(driveNumber > volunteerNumber) {
			return "ドライブ";
		} else {
			return "中立的";
		}
	}

	/**
	 * 診断結果から思考のタイプを返す
	 * */
	public String getThinkingType() {

		// 診断しているかを確認
		if (!checkResult()) {
			return "診断していません";
		}

		if (analyzeNumber < createNumber) {
			return "クリエイト";
		} else if(analyzeNumber > createNumber) {
			return "アナライズ";
		} else {
			return "中立的";
		}
	}

	/**
	 * 診断しているかを判断
	 * */
	public boolean checkResult() {
		int total = driveNumber + volunteerNumber +analyzeNumber + createNumber;
		if (total == 30) {
			return true;
		} else {
			return false;
		}
	}
}

src/main/java/jp/co/surveyAlh/form/UserForm.java
package jp.co.surveyAlh.form;

public class UserForm {

	private int id;
	private String loginId;
	private String name;
	private String password;
	private String passwordConfirmation;


	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public void setPasswordConfirmation(String passwordConfirmation) {
		this.passwordConfirmation = passwordConfirmation;
	}
	public String getLoginId() {
		return loginId;
	}
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getPasswordConfirmation() {
		return passwordConfirmation;
	}
	public void setPasswordConfirmtion(String passwordConfirmation) {
		this.passwordConfirmation = passwordConfirmation;
	}
}

src/main/java/jp/co/surveyAlh/controller/HistoryController.java
package jp.co.surveyAlh.controller;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.surveyAlh.dto.ResultDto;
import jp.co.surveyAlh.dto.UserDto;
import jp.co.surveyAlh.service.ResultService;

@Controller
public class HistoryController {
	@Autowired
	private ResultService resultService;

	@RequestMapping(value="history", method = RequestMethod.GET)
	public String doHistory(Model model, HttpServletRequest req){
		UserDto userDto = (UserDto) req.getSession().getAttribute("loginUser");
		List<ResultDto> results = resultService.getResult(userDto.getId());

		model.addAttribute("results", results);
		return "History";
	}
}

src/main/java/jp/co/surveyAlh/controller/LoginController.java
package jp.co.surveyAlh.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.surveyAlh.dto.UserDto;
import jp.co.surveyAlh.form.UserForm;
import jp.co.surveyAlh.service.UserService;

@Controller
public class LoginController {

	@Autowired
	private UserService userService;

	@RequestMapping(value="/login", method=RequestMethod.GET)
	public String login(Model model, HttpServletRequest req) {

		UserForm form = new UserForm();
		model.addAttribute("loginForm", form);
		return "Login";
	}

	@RequestMapping(value="/login", method=RequestMethod.POST)
	public String login(@ModelAttribute UserForm form, Model model, HttpServletRequest req) {


		// フォーム情報を取得
		String loginId = form.getLoginId();
		String password = form.getPassword();

		// 特定のユーザーを取得
		UserDto userDto = userService.getUser(loginId, password);

		if (userDto != null ) {

			// ログイン情報をセッションに設定
			req.getSession().setAttribute("loginUser", userDto);
			return "redirect:/";
		} else {

			model.addAttribute("loginForm", form);
			return "Login";
		}
	}

	@RequestMapping(value="/logout", method=RequestMethod.GET)
	public String logout( HttpServletRequest req) {
		HttpSession session = req.getSession();
		session.setAttribute("loginUser", null);
		return "redirect:/login";
	}
}

src/main/java/jp/co/surveyAlh/controller/MypageController.java
package jp.co.surveyAlh.controller;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.surveyAlh.dto.ResultDto;
import jp.co.surveyAlh.dto.SurveyDto;
import jp.co.surveyAlh.dto.UserDto;
import jp.co.surveyAlh.service.ResultService;
import jp.co.surveyAlh.service.SurveyService;

@Controller
public class MypageController {

	@Autowired
	private SurveyService surveyService;
	@Autowired
	private ResultService resultService;

	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String mypage(Model model, HttpServletRequest req) {

		// ログインユーザーのIDを取得
		HttpSession session = req.getSession();
		UserDto loginUser = (UserDto) session.getAttribute("loginUser");
		int userId = loginUser.getId();

		// 最新の診断結果を取得
		ResultDto newResult = resultService.getNewResult(userId);
		List<SurveyDto> surveys = surveyService.getSurveys();
		model.addAttribute("newResult", newResult);
		model.addAttribute("surveys", surveys);
		return "Mypage";
	}
}

src/main/java/jp/co/surveyAlh/controller/SignupController.java
package jp.co.surveyAlh.controller;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.BeanUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.surveyAlh.dto.UserDto;
import jp.co.surveyAlh.form.UserForm;
import jp.co.surveyAlh.form.validation.SignupValidation;
import jp.co.surveyAlh.service.UserService;

@Controller
public class SignupController {

	@Autowired
	private UserService userService;

	// 新規登録画面表示
	@RequestMapping(value = "/signup", method = RequestMethod.GET)
	public String signUp(Model model) {

		// フォームの作成
		UserForm form = new UserForm();
		model.addAttribute("userForm", form);
		return "Signup";
	}

	@RequestMapping(value = "/signup", method = RequestMethod.POST)
	public String signup(@ModelAttribute UserForm form, Model model, HttpServletRequest req ) {

		List<String> messages = new ArrayList<String>();

		if (SignupValidation.isValid(form, messages, userService)) {

			UserDto userDto = new UserDto();
			BeanUtils.copyProperties(form, userDto);
			userService.insert(userDto);
			UserDto loginUser = userService.getUser(form.getLoginId(), form.getPassword());

			// ログイン処理
			req.getSession().setAttribute("loginUser", loginUser);
			return "redirect:/";
		} else {

			model.addAttribute("errorMessages", messages);
			return "Signup";
		}
	}
}

src/main/java/jp/co/surveyAlh/controller/SurveyController.java
package jp.co.surveyAlh.controller;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import jp.co.surveyAlh.dto.SurveyDto;
import jp.co.surveyAlh.dto.UserDto;
import jp.co.surveyAlh.form.AnswerForm;
import jp.co.surveyAlh.form.AnswerParentForm;
import jp.co.surveyAlh.service.AnswerService;
import jp.co.surveyAlh.service.SurveyService;

@Controller
public class SurveyController {

	@Autowired
	private SurveyService surveyService;

	@Autowired
	private AnswerService answerService;

	@RequestMapping(value="survey", method = RequestMethod.GET)
	public String doSurvey(@RequestParam("id")int surveyId, Model model,HttpServletRequest req){
		//survey.jspで表示する質問を取ってくる(Dtoの中身は確認しておいてください)
		List<SurveyDto> surveys = surveyService.getSurvey(surveyId);

		//回答フォームの初期設定をしてとって来る
		List<AnswerForm> aForms = answerService.getAnswerForm(surveys);
		AnswerParentForm apForm = new AnswerParentForm();
		apForm.setAnswerForm(aForms);
		model.addAttribute("surveys", surveys);
		model.addAttribute("apForm",apForm);
		return "Survey";
	}

	@RequestMapping(value="survey", method = RequestMethod.POST)
	public String postResult(@ModelAttribute AnswerParentForm apForm, Model model){
		List<AnswerForm> aForms = apForm.getAnswerForm();

		answerService.setAnswer(aForms);

		return "redirect:/";
	}
}

src/main/java/jp/co/surveyAlh/controller/UsersController.java
package jp.co.surveyAlh.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.surveyAlh.dto.UserDto;
import jp.co.surveyAlh.service.UserService;

@Controller
public class UsersController {

	@Autowired
	private UserService userService;

	@RequestMapping(value="/users", method=RequestMethod.GET)
	public String users(Model model) {

		List<UserDto> users = userService.getUsers();

		model.addAttribute("users", users);
		return "Users";
	}
}

src/main/webapp/WEB-INF/view/ErrorMessages.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<c:if test="${not empty errorMessages }">
	<div class="error-messages">
		<ul>
			<c:forEach items="${errorMessages }" var="message">
				<li><c:out value="${message}" /></li>
			</c:forEach>
		</ul>
	</div>
	<c:remove var="errorMessages" scope="session"/>
</c:if>

src/main/webapp/WEB-INF/view/Header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<link href="<c:url value="/resources/css/style.css" />" rel="stylesheet">
<header class="site-header clearfix">
		<h1 class="site-logo">
			<a href="./" id="logo-decoration">Survey</a>
		</h1>
		<nav class="gnav">
			<ul class="gnav__menu">
				<c:if test="${empty loginUser}">
					<li class="gnav__menu__item"><a href="./login">ログイン</a></li>
					<li class="gnav__menu__item"><a href="./signup">サインアップ</a></li>
				</c:if>
				<c:if test="${ not empty loginUser }">
					<li class="gnav__menu__item"><a href="./history">履歴</a></li>
					<li class="gnav__menu__item"><a href="./users">ユーザー一覧</a></li>
					<li class="gnav__menu__item"><a href="./logout">ログアウト</a></li>
				</c:if>
			</ul>
		</nav>
</header>

src/main/webapp/WEB-INF/view/History.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>履歴</title>
</head>
<body>
	<%@ include file="Header.jsp"%>
	<div class="main-contents">
		<h2>履歴</h2>
		<div class="chart-history">
			<canvas id="myChart"></canvas>
		</div>

		<table class="history-table">
			<tr>
				<th>回答日時</th>
				<th>性格</th>
				<th>思考</th>
			</tr>

			<c:forEach items="${results}" var="result">
				<tr>
					<td><fmt:formatDate value="${result.createdDate}"
							pattern="yyyy/MM/dd" /></td>
					<td><c:out value="${result.personalityType}" /></td>
					<td><c:out value="${result.thinkingType}" /></td>
				</tr>
			</c:forEach>
		</table>

		<c:forEach items="${results}" var="result">
			<div id="createdDate" hidden>
				<fmt:formatDate value="${result.createdDate}"
							pattern="yyyy/MM/dd" />
			</div>
			<div id="driveNumber" hidden>
				<c:out value="${result.driveNumber}" />
			</div>
			<div id="volunteerNumber" hidden>
				<c:out value="${result.volunteerNumber}" />
			</div>
			<div id="analyzeNumber" hidden>
				<c:out value="${result.analyzeNumber}" />
			</div>
			<div id="createNumber" hidden>
				<c:out value="${result.createNumber}" />
			</div>
		</c:forEach>
	</div>
</body>
<script>
	var ctx = document.getElementById("myChart");
	var created_date = document.getElementById("createdDate").textContent;
	var drive_number = document.getElementById("driveNumber").textContent;
	var volunteer_number = document.getElementById("volunteerNumber").textContent;
	var analyze_number = document.getElementById("analyzeNumber").textContent;
	var create_number = document.getElementById("createNumber").textContent;

	var myChart = new Chart(ctx, {
		type : 'radar',
		data : {
			labels : [ "ドライブ", "クリエイト", "ボランティア", "アナライズ" ],
			datasets : [ {
				label : created_date,
				backgroundColor : "rgba(153,255,51,0.4)",
				borderColor : "rgba(153,255,51,1)",
				data : [ drive_number, create_number, volunteer_number,
						analyze_number ]
			} ]
		},
		options : {
			scale : {
				ticks : {
					max : 20,
					min : 0
				}
			}
		}
	});
</script>
</html>

src/main/webapp/WEB-INF/view/Login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ログイン</title>
</head>
<body>
	<%@ include file="Header.jsp"%>
	<div class="main-contents">
		<h2>ログイン</h2>

		<%@ include file="ErrorMessages.jsp" %>

		<form:form modelAttribute="loginForm">
			<div>
				<label>ログインID</label>
				<form:input path="loginId" />
			</div>
			<div>
				<label>パスワード</label>
				<form:input type="password" path="password" />
			</div>

			<input type="submit">
		</form:form>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/view/Mypage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>マイページ</title>
</head>
<body>

	<%@ include file="Header.jsp"%>

	<div class="main-contents">
		<div class="survey-form">
			<form action="survey">
				<select name="id">
					<c:forEach items="${surveys }" var="survey">
						<option value="<c:out value="${survey.id }"/>"><c:out
								value="${survey.surveyTitle}" /></option>
					</c:forEach>
				</select> <input type="submit" class="square_btn select_survey_btn submit" value="このアンケートへ" />
			</form>
		</div>

		<!-- 最新の診断結果をチャートで表示 -->
		<div class="mypage-chart">
			<h3>最新の診断結果</h3>
			<!-- 診断内容 -->
			<div class="mypage-table">
				<table>
					<thead>
						<tr>
							<th>性格</th>
							<th>思考</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td><c:out value="${newResult.personalityType }" /></td>
							<td><c:out value="${newResult.thinkingType }" /></td>
						</tr>
					</tbody>
				</table>
			</div>
			<canvas id="myChart"></canvas>
		</div>
		<!-- チャートの値用 -->
		<div id="driveNumber" hidden>
			<c:out value="${newResult.driveNumber}" />
		</div>
		<div id="volunteerNumber" hidden>
			<c:out value="${newResult.volunteerNumber}" />
		</div>
		<div id="analyzeNumber" hidden>
			<c:out value="${newResult.analyzeNumber}" />
		</div>
		<div id="createNumber" hidden>
			<c:out value="${newResult.createNumber}" />
		</div>
	</div>
</body>
<script>
	var ctx = document.getElementById("myChart");
	var drive_number = document.getElementById("driveNumber").textContent;
	var volunteer_number = document.getElementById("volunteerNumber").textContent;
	var analyze_number = document.getElementById("analyzeNumber").textContent;
	var create_number = document.getElementById("createNumber").textContent;
	var myChart = new Chart(ctx, {
		type : 'radar',
		data : {
			labels : [ "ドライブ", "クリエイト", "ボランティア", "アナライズ" ],
			datasets : [ {
				label : 'apples',
				backgroundColor : "rgba(153,255,51,0.4)",
				borderColor : "rgba(153,255,51,1)",
				data : [ drive_number, create_number, volunteer_number,
						analyze_number ]
			} ]
		},
		options : {
			scale : {
				ticks : {
					max : 20,
					min : 0
				}
			}
		}
	});
</script>
</html>

src/main/webapp/WEB-INF/view/Signup.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>新規登録</title>
</head>
<body>
	<%@ include file="Header.jsp"%>

	<h2>新規登録</h2>
	<div class="main-contents">
	<%@ include file="ErrorMessages.jsp" %>

	<form:form modelAttribute="userForm">
		<div>
			<label>ログインID</label>
			<form:input path="loginId"/>
		</div>
		<div>
			<label>名前</label>
			<form:input path="name"/>
		</div>
		<div>
			<label>パスワード</label>
			<form:input  type="password" path="password"/>
		</div>
		<div>
			<label>パスワード（確認用）</label>
			<form:input type="password" path="passwordConfirmation"/>
		</div>

		<input type="submit" >
	</form:form>
	</div>

</body>
</html>

src/main/webapp/WEB-INF/view/Survey.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta charset=UTF-8>
<title>アンケート</title>
<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
<link href="<c:url value="/resources/css/survey.css" />"
	rel="stylesheet">
<script src="<c:url value="/resources/js/survey.js" />"></script>

</head>
<body>
	<%@ include file="Header.jsp"%>

	<div class="main-contents">
		<div id="survey">
		<h2><c:out value="${surveys[1].surveyTitle }" /></h2>
			<form:form method="POST" modelAttribute="apForm" id="answerquestion">
				<c:forEach items="${apForm.getAnswerForm() }" varStatus="status">
					<div class="questions" id="${status.index }">
						<div class="questionTitle" style="text-align: left;">
							問<c:out value="${surveys[status.index].questionNumber}" />
							<c:out value="${surveys[status.index].title}" />
						</div>
						<div class="choiceA">
							<div class="choice-box">
								<c:out value="${surveys[status.index].choiceA }" />
							</div>

							<form:radiobutton id="rbA${status.index }" label="◎" value="2"
								path="answerForm[${status.index}].driveNumber" />
							<form:radiobutton id="rbA${status.index }" label="○" value="1"
								path="answerForm[${status.index}].driveNumber" />
							<form:radiobutton id="rbA${status.index }" label="×" value="0"
								path="answerForm[${status.index}].driveNumber" checked="checked" />
						</div>
						<div class="choiceB">
							<div class="choice-box">
							<c:out value="${surveys[status.index].choiceB }" />
							</div>
							<form:radiobutton id="rbB${status.index }" label="◎" value="2"
								path="answerForm[${status.index}].analyzeNumber" />
							<form:radiobutton id="rbB${status.index }" label="○" value="1"
								path="answerForm[${status.index}].analyzeNumber" />
							<form:radiobutton id="rbB${status.index }" label="×" value="0"
								path="answerForm[${status.index}].analyzeNumber"
								checked="checked" />
						</div>
						<div class="choiceC">
							<div class="choice-box">
							<c:out value="${surveys[status.index].choiceC }" />
							</div>
							<form:radiobutton id="rbC${status.index }" label="◎" value="2"
								path="answerForm[${status.index}].createNumber" />
							<form:radiobutton id="rbC${status.index }" label="○" value="1"
								path="answerForm[${status.index}].createNumber" />
							<form:radiobutton id="rbC${status.index }" label="×" value="0"
								path="answerForm[${status.index}].createNumber"
								checked="checked" />
						</div>
						<div class="choiceD">
							<div class="choice-box">
							<c:out value="${surveys[status.index].choiceD }" />
							</div>
							<form:radiobutton id="rbD${status.index }" label="◎" value="2"
								path="answerForm[${status.index}].volunteerNumber" />
							<form:radiobutton id="rbD${status.index }" label="○" value="1"
								path="answerForm[${status.index}].volunteerNumber" />
							<form:radiobutton id="rbD${status.index }" label="×" value="0"
								path="answerForm[${status.index}].volunteerNumber"
								checked="checked" />
						</div>
						<form:hidden path="answerForm[${status.index}].userId"
							value="${loginUser.id }" />
						<form:hidden path="answerForm[${status.index}].questionId"
							value="${surveys[status.index].questionId}" />
						<form:hidden path="answerForm[${status.index}].surveyId"
							value="${surveys[status.index].surveyId}" />
						<c:if test="${status.index == 9 }">
							<input class="select_survey_btn" type="submit" id="submit" value="アンケートに回答" />
						</c:if>
					</div>

				</c:forEach>
			</form:form>
			<div id="next" class="select_survey_btn">next</div>
			<div id="back" >back</div>
		</div>
	</div>

</body>
</html>

src/main/webapp/WEB-INF/view/Users.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>ユーザー一覧</title>
</head>
<body>

	<%@ include file="Header.jsp"%>
	<div class="main-contents">

		<table>
			<thead>
				<tr>
					<th>ユーザー名</th>
					<th>性格</th>
					<th>思考</th>
				</tr>
			</thead>

			<tbody>
				<c:forEach items="${users}" var="user">
					<tr>
						<!-- ユーザー名 -->
						<td><c:out value="${user.name }" /></td>
						<!-- 診断結果 -->
						<td><c:out value="${user.personalityType }" /></td>
						<td><c:out value="${user.thinkingType }" /></td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
	</div>
</body>
</html>

src/main/webapp/WEB-INF/view/showMessage.jsp
<!DOCTYPE html>

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<html>
	<head>
		<meta charset="utf-8">
		<title>Welcome</title>
	</head>
	<body>
		<h2>${message}</h2>
	</body>
</html>